apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 29092
      targetPort: lc
      protocol: TCP
      name: lc
  clusterIP: None
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: kafka
    app.kubernetes.io/part-of: ftgo
