apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-ui
      app.kubernetes.io/component: kafka-ui
      app.kubernetes.io/part-of: ftgo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-ui
        app.kubernetes.io/component: kafka-ui
        app.kubernetes.io/part-of: ftgo
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "local"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka.default.svc.cluster.local:29092"
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: zookeeper.default.svc.cluster.local:2181
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: 128Mi
              cpu: 0.05
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
