apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - port: 2181
      name: client
  selector:
    app.kubernets.io/name: zookeeper
    app.kubernets.io/component: zookeeper
    app.kubernetes.io/part-of: ftgo
