apiVersion: v1
kind: Service
metadata:
  name: restaurant-service-db
  labels:
    app.kubernets.io/name: restaurant-service-db
spec:
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernets.io/name: restaurant-service-db
    app.kubernets.io/component: db
    app.kubernetes.io/part-of: ftgo
