apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service-app
  labels:
    {{- include "restaurant-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "restaurant-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "restaurant-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8101
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://restaurant-service-db.default.svc.cluster.local/ftgo-restaurant-service"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
          livenessProbe:
            httpGet:
              path: /ping/
              port: http
          readinessProbe:
            httpGet:
              path: /ping/?include_db=true
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
